apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: eduazureregistry.azurecr.io/backend-java
    newTag: main-20240724074923

commonLabels:
  app: backend-java
  environment: dev
